# Generated by Django 5.2.3 on 2025-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateField()),
                ('category_name', models.CharField()),
            ],
        ),
    ]
